# Generated by Django 4.2.28 on 2026-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'En Attente'), ('SUSPENDED', 'Suspendu'), ('DELETED', 'Supprimé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
