# Generated by Django 4.2.28 on 2026-02-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
    ]
