export const EU_REGULATORY_CATEGORIES = [
    {
        group: 'Batteries (UE 2023/1542)',
        options: [
            'Portable battery',
            'Portable battery of general use',
            'LMT battery (Light Means of Transport)',
            'SLI battery (Starting, Lighting, Ignition)',
            'Industrial battery',
            'Electric vehicle battery',
        ],
    },
    {
        group: 'ESPR 2025-2030',
        options: [
            'Textiles',
            'Furniture',
            'Steel',
            'Aluminium',
            'Tyres',
            'Mattresses',
            'Electrical and electronic equipment (horizontal measures)',
            'Energy-related products',
        ],
    },
    {
        group: 'ESPR (pré-études)',
        options: [
            'Detergents',
            'Paints',
            'Lubricants',
            'Iron and steel',
            'Non-ferrous metal products',
            'ICT and electronics',
        ],
    },
];

export const EU_CERTIFICATION_SUGGESTIONS = [
    'CE',
    'RoHS',
    'REACH',
    'WEEE',
    'Ecodesign / ErP',
    'EU Energy Label',
    'Battery Passport',
    'EN 62133',
    'IEC 62133',
    'UN 38.3',
    'ISO 9001',
    'ISO 14001',
    'ISO 45001',
    'ISO 50001',
    'ISO 14064',
    'ISO 14067',
    'ISO 14040',
    'ISO 14044',
    'EMAS',
    'EU Ecolabel',
    'FSC',
    'PEFC',
    'Oeko-Tex Standard 100',
    'GOTS',
    'GRS (Global Recycled Standard)',
    'RCS (Recycled Claim Standard)',
    'Bluesign',
    'Cradle to Cradle',
    'Fairtrade',
    'SA8000',
    'B Corp',
    'TCO Certified',
    'Energy Star',
    'EPEAT',
    'GS (Geprufte Sicherheit)',
    'TUV',
    'UL',
    'NF Environnement',
    'Blue Angel',
    'Nordic Swan',
];

export const FLAT_EU_CATEGORY_OPTIONS = EU_REGULATORY_CATEGORIES.flatMap((group) => group.options);
