# Generated by Django 4.2.30 on 2026-04-11 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Fabricant')),
                ('is_main_product', models.BooleanField(default=False, verbose_name='Produit principal')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fournisseur')),
                ('material_composition', models.JSONField(blank=True, default=dict, help_text='Ex: {"plastic": 60, "metal": 30, "glass": 10}', verbose_name='Composition matérielle')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Ex: ["CE", "RoHS", "REACH"]', verbose_name='Certifications')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=14, verbose_name='GTIN')),
                ('supplier_submitted', models.BooleanField(default=False, verbose_name='Soumis par le fournisseur')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
                ('components', models.ManyToManyField(blank=True, related_name='used_in', to='products.item', verbose_name='Composants')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('password_hash', models.CharField(blank=True, max_length=256, null=True, verbose_name='Hash du mot de passe')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Révoqué')),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.item', verbose_name='Composant')),
            ],
            options={
                'verbose_name': 'Lien fournisseur',
                'verbose_name_plural': 'Liens fournisseur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de snapshot')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload (JSON)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='products.item', verbose_name='Produit principal')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Date de fabrication réelle')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('production_batch', models.CharField(blank=True, max_length=100, verbose_name='Lot de production')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twins', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twins', to='products.snapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Digital Twin',
                'verbose_name_plural': 'Digital Twins',
                'ordering': ['-created_at'],
            },
        ),
    ]
