# Generated by Arabica on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_brand_item_category_item_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de version'),
        ),
    ]

