# Generated by Django 5.2.11 on 2026-02-13 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='supplier_locked',
            field=models.BooleanField(default=False, verbose_name='Verrouillé (fournisseur)'),
        ),
        migrations.AddField(
            model_name='component',
            name='supplier_validated',
            field=models.BooleanField(default=False, verbose_name='Validé par le fournisseur'),
        ),
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('password_hash', models.CharField(blank=True, max_length=256, null=True, verbose_name='Hash du mot de passe')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Révoqué')),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du fournisseur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='products.component', verbose_name='Composant')),
            ],
            options={
                'verbose_name': 'Lien fournisseur',
                'verbose_name_plural': 'Liens fournisseur',
                'ordering': ['-created_at'],
            },
        ),
    ]
