# Generated by Django 5.2.11 on 2026-02-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_component_supplier_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
