# Generated by Django 4.2.30 on 2026-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_supplierlink_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["CE", "RoHS", "REACH"]', verbose_name='Certifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_composition',
            field=models.JSONField(blank=True, default=dict, help_text='Ex: {"steel": 70, "plastic": 30}', verbose_name='Composition matérielle'),
        ),
    ]
