# Generated by Django 4.2.28 on 2026-02-05 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du composant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Fabricant')),
                ('material_composition', models.JSONField(blank=True, default=dict, help_text='Ex: {"plastic": 60, "metal": 30, "glass": 10}', verbose_name='Composition matérielle')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Ex: ["CE", "RoHS", "REACH"]', verbose_name='Certifications')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=14, verbose_name='GTIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gtin', models.CharField(help_text='Global Trade Item Number - unique identifier', max_length=14, unique=True, verbose_name='GTIN')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('COMPLETE', 'Complet'), ('LOCKED', 'Verrouillé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de modèle')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('json_ld', models.JSONField(blank=True, default=dict, help_text='Digital Product Passport au format JSON-LD', verbose_name='JSON-LD DPP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
                ('components', models.ManyToManyField(blank=True, related_name='products', to='products.component', verbose_name='Composants')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('production_batch', models.CharField(blank=True, max_length=100, verbose_name='Lot de production')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Instance de Produit',
                'verbose_name_plural': 'Instances de Produit',
                'ordering': ['-created_at'],
            },
        ),
    ]
