# Generated by Django 4.2.28 on 2026-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Global Trade Item Number - unique identifier', max_length=14, null=True, unique=True, verbose_name='GTIN'),
        ),
    ]
