# Generated by Django 4.2.28 on 2026-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_gtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_date',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fabrication réelle'),
        ),
    ]
